###############################################################################
#  Copyright 2013 - 2018 Software AG, Darmstadt, Germany and/or its licensors
#
#   SPDX-License-Identifier: Apache-2.0
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
###############################################################################
apiVersion: v1
data:
  com.softwareag.registry.handler.pid-CC.properties: |-
    registry.target=(name=CC)
    executor.name=cron
    executor.period=1000
kind: ConfigMap
metadata:
  name: spm-prop-1
  namespace: um-is-namespace
---
apiVersion: v1
data:
  com.softwareag.registry.pid-CC.properties: |-
    registry.root=.
    registry.namespaces.root=.
    name=CC\r\nrepository.target=(name\\=CC)
    registry.factory.target=(component.name\\=com.webmethods.deployer.common.acdl.AcdlCompositeAsset)
    type=com.webmethods.deployer.common.acdl.AcdlCompositeAsset
    binary.repository.target=(name\\=CC)
kind: ConfigMap
metadata:
  name: spm-prop-2
  namespace: um-is-namespace
---
apiVersion: v1
data:
  com.softwareag.repository.git.pid-CC.properties: |-
    remoteStore=@env:LAR_REPO_URL
    #branch=$env:LAR_REPO_BRANCH
    name=CC
    type=git
    localStore=file\\:/opt/softwareag/profiles/SPM/data/git/lar
kind: ConfigMap
metadata:
  name: spm-prop-3
  namespace: um-is-namespace
apiVersion: v1
data:
  com.softwareag.registry.handler.pid-CC.properties: |
    registry.target: "(name=CC)"
    executor.name: "cron"
    executor.period: "1000"
  com.softwareag.registry.pid-CC.properties: |
    registry.root: "."
    registry.namespaces.root: "."
    name: "CC"
    repository.target: "(name\=CC)"
    registry.factory.target: "(component.name\=com.webmethods.deployer.common.acdl.AcdlCompositeAsset)"
    type: "com.webmethods.deployer.common.acdl.AcdlCompositeAsset"
    binary.repository.target: "(name\=CC)"
  com.softwareag.repository.git.pid-CC.properties: |
    name: "CC"
    type: "git"
    localStore: "file\:/opt/softwareag/profiles/SPM/data/git/lar"
